### ISSUE TITLE
Cannot follow the tutorial "tidysdm overview"

### ISSUE THREAD

**Issue by ManuelSpinola** [EvolEcolGroup/tidysdm#31] opened 2024-01-23 02:42 UTC
I got an error following the tutorial "tidysdm overview"

library(tidysdm)
library(pastclim)

land_mask <- get_land_mask(time_ce = 1985, dataset = "WorldClim_2.1_10m")
Error in check_var_downloaded(bio_variables, dataset) : 
  variable (bio01) not yet downloaded, use `download_dataset()`

**Comment by dramanica** [comment] 2024-01-23 06:06
Thanks for reporting this issue! The problem is that the Worldclim dataset has not been downloaded on your machine yet. That can be fixed with:

`download_dataset(dataset = "WorldClim_2.1_10m")`

I have updated the vignette on our website to fix that omission (you might need to refresh the page on your browser to see the changes). Let me know if you encounter any further issue.

**Closed by dramanica** 2024-01-23 06:06 UTC
